import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const ScenicSpotSchema = new mongoose.Schema({
  name: String,
  province: String,
  city: String,
  description: String,
  highlights: [String],
  ticketInfo: {
    price: Number,
    description: String
  },
  openTime: String,
  rating: Number,
  images: [String],
  location: {
    type: { type: String, default: 'Point' },
    coordinates: { type: [Number], default: [0, 0] }
  }
});

const ScenicSpot = mongoose.model('ScenicSpot', ScenicSpotSchema);

// 官方358个5A级景区完整名单
const official5ASpots = [
  { name: "故宫博物院", province: "北京市" },
  { name: "天坛公园", province: "北京市" },
  { name: "颐和园", province: "北京市" },
  { name: "八达岭-慕田峪长城旅游区", province: "北京市" },
  { name: "明十三陵景区", province: "北京市" },
  { name: "北京奥林匹克公园", province: "北京市" },
  { name: "恭王府景区", province: "北京市" },
  { name: "北京（通州）大运河文化旅游景区", province: "北京市" },
  { name: "圆明园遗址公园景区", province: "北京市" },
  { name: "东方明珠广播电视塔", province: "上海市" },
  { name: "上海野生动物园", province: "上海市" },
  { name: "上海科技馆", province: "上海市" },
  { name: "中国共产党一大·二大·四大纪念馆景区", province: "上海市" },
  { name: "西沙明珠湖景区", province: "上海市" },
  { name: "天津古文化街旅游区（津门故里）", province: "天津市" },
  { name: "天津盘山风景名胜区", province: "天津市" },
  { name: "承德避暑山庄及周围寺庙景区", province: "河北省" },
  { name: "秦皇岛山海关景区", province: "河北省" },
  { name: "保定安新白洋淀景区", province: "河北省" },
  { name: "保定涞水县野三坡景区", province: "河北省" },
  { name: "石家庄平山县西柏坡景区", province: "河北省" },
  { name: "唐山清东陵景区", province: "河北省" },
  { name: "邯郸娲皇宫景区", province: "河北省" },
  { name: "保定白石山景区", province: "河北省" },
  { name: "邯郸广府古城景区", province: "河北省" },
  { name: "秦皇岛北戴河景区", province: "河北省" },
  { name: "唐山南湖·开滦旅游景区", province: "河北省" },
  { name: "衡水湖旅游景区", province: "河北省" },
  { name: "保定市清西陵景区", province: "河北省" },
  { name: "承德市金山岭长城景区", province: "河北省" },
  { name: "大同云冈石窟", province: "山西省" },
  { name: "忻州五台山风景名胜区", province: "山西省" },
  { name: "晋城阳城皇城相府生态文化旅游区", province: "山西省" },
  { name: "晋中绵山风景名胜区", province: "山西省" },
  { name: "长治壶关太行山大峡谷", province: "山西省" },
  { name: "临汾洪洞大槐树寻根祭祖园", province: "山西省" },
  { name: "运城盐湖景区", province: "山西省" },
  { name: "吕梁汾阳杏花村汾酒文化景区", province: "山西省" },
  { name: "太原晋祠天龙山景区", province: "山西省" },
  { name: "朔州应县木塔景区", province: "山西省" },
  { name: "晋中市平遥古城景区", province: "山西省" },
  { name: "忻州市雁门关景区", province: "山西省" },
  { name: "临汾市云丘山景区", province: "山西省" },
  { name: "黄河壶口瀑布旅游区", province: "山西省" },
  { name: "晋中市乔家大院景区", province: "山西省" },
  { name: "鄂尔多斯达拉特旗响沙湾旅游景区", province: "内蒙古自治区" },
  { name: "鄂尔多斯伊金霍洛旗成吉思汗陵旅游区", province: "内蒙古自治区" },
  { name: "呼伦贝尔满洲里市中俄边境旅游区", province: "内蒙古自治区" },
  { name: "兴安盟阿尔山-柴河旅游景区", province: "内蒙古自治区" },
  { name: "赤峰克什克腾石阵景区", province: "内蒙古自治区" },
  { name: "阿拉善盟胡杨林旅游区", province: "内蒙古自治区" },
  { name: "呼和浩特敕勒川草原文化旅游区", province: "内蒙古自治区" },
  { name: "赤峰市阿斯哈图石林景区", province: "内蒙古自治区" },
  { name: "呼伦贝尔市呼伦贝尔大草原·莫尔格勒河景区", province: "内蒙古自治区" },
  { name: "呼和浩特市老牛湾黄河大峡谷旅游区", province: "内蒙古自治区" },
  { name: "沈阳植物园", province: "辽宁省" },
  { name: "大连老虎滩海洋公园-老虎滩极地馆", province: "辽宁省" },
  { name: "大连金石滩景区", province: "辽宁省" },
  { name: "本溪水洞景区", province: "辽宁省" },
  { name: "鞍山千山景区", province: "辽宁省" },
  { name: "丹东鸭绿江断桥景区", province: "辽宁省" },
  { name: "盘锦红海滩风景廊道", province: "辽宁省" },
  { name: "本溪市五女山景区", province: "辽宁省" },
  { name: "长白山景区", province: "吉林省" },
  { name: "长春伪满皇宫博物院", province: "吉林省" },
  { name: "长春净月潭景区", province: "吉林省" },
  { name: "长春长影世纪城", province: "吉林省" },
  { name: "延边朝鲜族自治州敦化六鼎山文化旅游区", province: "吉林省" },
  { name: "吉林市万科松花湖度假区", province: "吉林省" },
  { name: "通化高句丽文物古迹景区", province: "吉林省" },
  { name: "白城向海国家级自然保护区", province: "吉林省" },
  { name: "长春市世界雕塑公园景区", province: "吉林省" },
  { name: "松原市前郭查干湖景区", province: "吉林省" },
  { name: "白城市大安嫩江湾旅游区", province: "吉林省" },
  { name: "哈尔滨太阳岛公园", province: "黑龙江省" },
  { name: "黑河五大连池景区", province: "黑龙江省" },
  { name: "牡丹江镜泊湖景区", province: "黑龙江省" },
  { name: "伊春汤旺河林海奇石景区", province: "黑龙江省" },
  { name: "大兴安岭漠河北极村旅游景区", province: "黑龙江省" },
  { name: "鸡西虎头旅游景区", province: "黑龙江省" },
  { name: "齐齐哈尔市扎龙生态旅游区", province: "黑龙江省" },
  { name: "苏州园林（拙政园、虎丘、留园）", province: "江苏省" },
  { name: "苏州周庄古镇景区", province: "江苏省" },
  { name: "南京钟山-中山陵园景区", province: "江苏省" },
  { name: "无锡灵山大佛景区", province: "江苏省" },
  { name: "无锡鼋头渚景区", province: "江苏省" },
  { name: "中央电视台无锡影视基地三国水浒城", province: "江苏省" },
  { name: "苏州同里古镇景区", province: "江苏省" },
  { name: "南京夫子庙-秦淮河风光带", province: "江苏省" },
  { name: "常州环球恐龙城", province: "江苏省" },
  { name: "扬州瘦西湖景区", province: "江苏省" },
  { name: "南通濠河景区", province: "江苏省" },
  { name: "泰州溱湖国家湿地公园", province: "江苏省" },
  { name: "苏州金鸡湖景区", province: "江苏省" },
  { name: "镇江三山（金山、焦山、北固山）", province: "江苏省" },
  { name: "苏州吴中太湖旅游区", province: "江苏省" },
  { name: "常熟沙家浜·虞山尚湖旅游区", province: "江苏省" },
  { name: "常州天目湖景区", province: "江苏省" },
  { name: "镇江句容茅山景区", province: "江苏省" },
  { name: "淮安周恩来故里旅游景区", province: "江苏省" },
  { name: "盐城大丰中华麋鹿园景区", province: "江苏省" },
  { name: "无锡惠山古镇景区", province: "江苏省" },
  { name: "连云港花果山景区", province: "江苏省" },
  { name: "宿迁项王故里景区", province: "江苏省" },
  { name: "徐州云龙湖景区", province: "江苏省" },
  { name: "盐城大纵湖旅游景区", province: "江苏省" },
  { name: "镇江丹阳中国眼镜城景区", province: "江苏省" },
  { name: "常州市春秋淹城旅游区", province: "江苏省" },
  { name: "宿迁市洪泽湖湿地景区", province: "江苏省" },
  { name: "连云港市连岛景区", province: "江苏省" },
  { name: "杭州西湖风景区", province: "浙江省" },
  { name: "温州雁荡山风景区", province: "浙江省" },
  { name: "舟山普陀山风景区", province: "浙江省" },
  { name: "杭州千岛湖风景区", province: "浙江省" },
  { name: "嘉兴乌镇古镇", province: "浙江省" },
  { name: "宁波奉化溪口-滕头旅游景区", province: "浙江省" },
  { name: "金华东阳横店影视城", province: "浙江省" },
  { name: "杭州西溪湿地旅游区", province: "浙江省" },
  { name: "嘉兴南湖旅游区", province: "浙江省" },
  { name: "绍兴鲁迅故里-沈园景区", province: "浙江省" },
  { name: "衢州江郎山-廿八都旅游区", province: "浙江省" },
  { name: "台州天台山景区", province: "浙江省" },
  { name: "丽水缙云仙都景区", province: "浙江省" },
  { name: "湖州南浔古镇景区", province: "浙江省" },
  { name: "台州神仙居景区", province: "浙江省" },
  { name: "丽水云和梯田景区", province: "浙江省" },
  { name: "温州刘伯温故里景区", province: "浙江省" },
  { name: "宁波天一阁·月湖景区", province: "浙江省" },
  { name: "舟山嵊泗列岛景区", province: "浙江省" },
  { name: "金华永康方岩景区", province: "浙江省" },
  { name: "台州府城文化旅游区", province: "浙江省" },
  { name: "衢州市根宫佛国文化旅游区", province: "浙江省" },
  { name: "嘉兴市西塘古镇旅游景区", province: "浙江省" },
  { name: "金华市双龙风景旅游区", province: "浙江省" },
  { name: "黄山风景区", province: "安徽省" },
  { name: "池州九华山风景区", province: "安徽省" },
  { name: "安庆天柱山风景区", province: "安徽省" },
  { name: "皖南古村落-西递宏村", province: "安徽省" },
  { name: "六安天堂寨旅游景区", province: "安徽省" },
  { name: "宣城绩溪龙川景区", province: "安徽省" },
  { name: "阜阳八里河风景区", province: "安徽省" },
  { name: "合肥三河古镇景区", province: "安徽省" },
  { name: "芜湖方特旅游区", province: "安徽省" },
  { name: "马鞍山采石矶文化生态旅游区", province: "安徽省" },
  { name: "铜陵大通古镇景区", province: "安徽省" },
  { name: "滁州琅琊山风景区", province: "安徽省" },
  { name: "宿州皇藏峪国家森林公园", province: "安徽省" },
  { name: "黄山市古徽州文化旅游区", province: "安徽省" },
  { name: "六安市万佛湖风景区", province: "安徽省" },
  { name: "厦门鼓浪屿风景名胜区", province: "福建省" },
  { name: "南平武夷山风景名胜区", province: "福建省" },
  { name: "福建土楼（永定·南靖）旅游景区", province: "福建省" },
  { name: "宁德屏南白水洋·鸳鸯溪旅游区", province: "福建省" },
  { name: "泉州清源山景区", province: "福建省" },
  { name: "三明泰宁风景旅游区", province: "福建省" },
  { name: "福州三坊七巷历史文化街区", province: "福建省" },
  { name: "龙岩古田旅游区", province: "福建省" },
  { name: "莆田湄洲岛妈祖文化旅游区", province: "福建省" },
  { name: "厦门园林植物园景区", province: "福建省" },
  { name: "漳州东山岛风动石景区", province: "福建省" },
  { name: "宁德市太姥山旅游区", province: "福建省" },
  { name: "厦门市厦门园林植物园景区", province: "福建省" },
  { name: "龙岩市冠豸山景区", province: "福建省" },
  { name: "九江庐山风景区", province: "江西省" },
  { name: "吉安井冈山风景旅游区", province: "江西省" },
  { name: "上饶三清山旅游景区", province: "江西省" },
  { name: "鹰潭龙虎山风景名胜区", province: "江西省" },
  { name: "景德镇古窑民俗博览区", province: "江西省" },
  { name: "赣州瑞金共和国摇篮景区", province: "江西省" },
  { name: "宜春明月山旅游区", province: "江西省" },
  { name: "抚州大觉山景区", province: "江西省" },
  { name: "上饶婺源江湾景区", province: "江西省" },
  { name: "南昌滕王阁旅游区", province: "江西省" },
  { name: "萍乡武功山风景区", province: "江西省" },
  { name: "九江庐山西海风景区", province: "江西省" },
  { name: "新余仙女湖风景区", province: "江西省" },
  { name: "上饶龟峰风景名胜区", province: "江西省" },
  { name: "赣州市三百山景区", province: "江西省" },
  { name: "上饶市篁岭景区", province: "江西省" },
  { name: "泰安泰山景区", province: "山东省" },
  { name: "烟台蓬莱阁-三仙山·八仙过海景区", province: "山东省" },
  { name: "济宁曲阜明故城（三孔）旅游区", province: "山东省" },
  { name: "青岛崂山风景区", province: "山东省" },
  { name: "威海刘公岛景区", province: "山东省" },
  { name: "烟台龙口南山景区", province: "山东省" },
  { name: "枣庄台儿庄古城景区", province: "山东省" },
  { name: "济南天下第一泉景区", province: "山东省" },
  { name: "潍坊青州古城旅游区", province: "山东省" },
  { name: "威海华夏城景区", province: "山东省" },
  { name: "东营黄河口生态旅游区", province: "山东省" },
  { name: "临沂沂蒙山旅游区", province: "山东省" },
  { name: "淄博周村古商城景区", province: "山东省" },
  { name: "济宁微山湖旅游区", province: "山东省" },
  { name: "济南千佛山风景区", province: "山东省" },
  { name: "临沂市萤火虫水洞·地下大峡谷旅游区", province: "山东省" },
  { name: "青岛市奥帆海洋文化旅游区", province: "山东省" },
  { name: "广州长隆旅游度假区", province: "广东省" },
  { name: "深圳华侨城旅游度假区", province: "广东省" },
  { name: "广州白云山风景区", province: "广东省" },
  { name: "梅州雁南飞茶田景区", province: "广东省" },
  { name: "清远连州地下河景区", province: "广东省" },
  { name: "韶关丹霞山景区", province: "广东省" },
  { name: "佛山西樵山景区", province: "广东省" },
  { name: "惠州罗浮山景区", province: "广东省" },
  { name: "佛山长鹿旅游休博园", province: "广东省" },
  { name: "深圳观澜湖休闲旅游区", province: "广东省" },
  { name: "阳江海陵岛大角湾海上丝路旅游区", province: "广东省" },
  { name: "中山孙中山故里旅游区", province: "广东省" },
  { name: "惠州西湖风景区", province: "广东省" },
  { name: "肇庆星湖风景名胜区", province: "广东省" },
  { name: "江门开平碉楼文化旅游区", province: "广东省" },
  { name: "河源市万绿湖风景区", province: "广东省" },
  { name: "桂林漓江风景区", province: "广西壮族自治区" },
  { name: "桂林兴安乐满地度假世界", province: "广西壮族自治区" },
  { name: "桂林独秀峰·王城景区", province: "广西壮族自治区" },
  { name: "南宁青秀山旅游区", province: "广西壮族自治区" },
  { name: "桂林两江四湖·象山景区", province: "广西壮族自治区" },
  { name: "崇左德天跨国瀑布景区", province: "广西壮族自治区" },
  { name: "百色起义纪念园景区", province: "广西壮族自治区" },
  { name: "北海涠洲岛南湾鳄鱼山景区", province: "广西壮族自治区" },
  { name: "贺州黄姚古镇景区", province: "广西壮族自治区" },
  { name: "柳州三江程阳八寨景区", province: "广西壮族自治区" },
  { name: "崇左市德天跨国瀑布景区", province: "广西壮族自治区" },
  { name: "崇左市花山岩画景区", province: "广西壮族自治区" },
  { name: "三亚南山文化旅游区", province: "海南省" },
  { name: "三亚南山大小洞天旅游区", province: "海南省" },
  { name: "保亭呀诺达雨林文化旅游区", province: "海南省" },
  { name: "陵水分界洲岛旅游区", province: "海南省" },
  { name: "保亭槟榔谷黎苗文化旅游区", province: "海南省" },
  { name: "三亚蜈支洲岛旅游区", province: "海南省" },
  { name: "海口观澜湖旅游度假区", province: "海南省" },
  { name: "三亚市天涯海角游览区", province: "海南省" },
  { name: "郑州登封嵩山少林景区", province: "河南省" },
  { name: "洛阳龙门石窟景区", province: "河南省" },
  { name: "焦作云台山-神农山-青天河风景区", province: "河南省" },
  { name: "安阳殷墟景区", province: "河南省" },
  { name: "洛阳嵩县白云山景区", province: "河南省" },
  { name: "开封清明上河园景区", province: "河南省" },
  { name: "平顶山尧山-中原大佛景区", province: "河南省" },
  { name: "洛阳老君山-鸡冠洞旅游区", province: "河南省" },
  { name: "南阳西峡伏牛山老界岭·恐龙遗址园", province: "河南省" },
  { name: "驻马店嵖岈山旅游景区", province: "河南省" },
  { name: "商丘永城芒砀山旅游景区", province: "河南省" },
  { name: "新乡八里沟景区", province: "河南省" },
  { name: "许昌鄢陵国家花木博览园", province: "河南省" },
  { name: "信阳鸡公山风景区", province: "河南省" },
  { name: "周口太昊陵景区", province: "河南省" },
  { name: "鹤壁淇县云梦山风景区", province: "河南省" },
  { name: "洛阳市龙潭大峡谷景区", province: "河南省" },
  { name: "安阳市红旗渠－太行大峡谷旅游景区", province: "河南省" },
  { name: "周口市太昊伏羲陵文化旅游区", province: "河南省" },
  { name: "新乡市宝泉旅游区", province: "河南省" },
  { name: "武汉黄鹤楼公园", province: "湖北省" },
  { name: "宜昌三峡大坝-屈原故里旅游区", province: "湖北省" },
  { name: "宜昌三峡人家风景区", province: "湖北省" },
  { name: "十堰武当山风景区", province: "湖北省" },
  { name: "恩施巴东神龙溪纤夫文化旅游区", province: "湖北省" },
  { name: "神农架生态旅游区", province: "湖北省" },
  { name: "宜昌清江画廊景区", province: "湖北省" },
  { name: "武汉东湖景区", province: "湖北省" },
  { name: "襄阳古隆中景区", province: "湖北省" },
  { name: "恩施大峡谷景区", province: "湖北省" },
  { name: "咸宁三国赤壁古战场景区", province: "湖北省" },
  { name: "荆州古城历史文化旅游区", province: "湖北省" },
  { name: "荆门明显陵文化旅游区", province: "湖北省" },
  { name: "孝感双峰山国家森林公园", province: "湖北省" },
  { name: "随州大洪山风景名胜区", province: "湖北省" },
  { name: "恩施州神农溪纤夫文化旅游区", province: "湖北省" },
  { name: "武汉市木兰文化生态旅游区", province: "湖北省" },
  { name: "恩施州腾龙洞景区", province: "湖北省" },
  { name: "宜昌市三峡大瀑布景区", province: "湖北省" },
  { name: "黄冈市麻城龟峰山景区", province: "湖北省" },
  { name: "张家界武陵源-天门山旅游区", province: "湖南省" },
  { name: "衡阳南岳衡山旅游区", province: "湖南省" },
  { name: "湘潭韶山旅游区", province: "湖南省" },
  { name: "岳阳岳阳楼-君山岛景区", province: "湖南省" },
  { name: "长沙岳麓山-橘子洲旅游区", province: "湖南省" },
  { name: "长沙花明楼景区", province: "湖南省" },
  { name: "郴州东江湖旅游区", province: "湖南省" },
  { name: "邵阳崀山景区", province: "湖南省" },
  { name: "株洲炎帝陵景区", province: "湖南省" },
  { name: "常德桃花源旅游区", province: "湖南省" },
  { name: "湘西凤凰古城景区", province: "湖南省" },
  { name: "永州九嶷山舜帝陵景区", province: "湖南省" },
  { name: "湘西州吉首市矮寨·十八洞·德夯大峡谷景区", province: "湖南省" },
  { name: "成都青城山-都江堰旅游景区", province: "四川省" },
  { name: "乐山峨眉山-乐山大佛景区", province: "四川省" },
  { name: "阿坝藏族羌族自治州九寨沟景区", province: "四川省" },
  { name: "阿坝藏族羌族自治州黄龙景区", province: "四川省" },
  { name: "绵阳北川羌城旅游区", province: "四川省" },
  { name: "阿坝藏族羌族自治州汶川特别旅游区", province: "四川省" },
  { name: "南充阆中古城旅游景区", province: "四川省" },
  { name: "广安市邓小平故里旅游区", province: "四川省" },
  { name: "广元剑门蜀道剑门关旅游景区", province: "四川省" },
  { name: "南充仪陇朱德故里景区", province: "四川省" },
  { name: "宜宾蜀南竹海景区", province: "四川省" },
  { name: "巴中光雾山旅游景区", province: "四川省" },
  { name: "甘孜州海螺沟景区", province: "四川省" },
  { name: "成都大熊猫繁育研究基地", province: "四川省" },
  { name: "雅安碧峰峡旅游景区", province: "四川省" },
  { name: "阿坝州四姑娘山景区", province: "四川省" },
  { name: "凉山州邛海-泸山景区", province: "四川省" },
  { name: "成都市安仁古镇景区", province: "四川省" },
  { name: "成都市天台山景区", province: "四川省" },
  { name: "大足石刻景区", province: "重庆市" },
  { name: "巫山小三峡-小小三峡", province: "重庆市" },
  { name: "武隆喀斯特旅游区", province: "重庆市" },
  { name: "酉阳桃花源景区", province: "重庆市" },
  { name: "万盛黑山谷-龙鳞石海景区", province: "重庆市" },
  { name: "南川金佛山景区", province: "重庆市" },
  { name: "合川钓鱼城古战场遗址景区", province: "重庆市" },
  { name: "江津四面山景区", province: "重庆市" },
  { name: "云阳龙缸景区", province: "重庆市" },
  { name: "彭水阿依河景区", province: "重庆市" },
  { name: "黔江濯水景区", province: "重庆市" },
  { name: "涪陵武陵山大裂谷景区", province: "重庆市" },
  { name: "白帝城·瞿塘峡景区", province: "重庆市" },
  { name: "安顺黄果树瀑布景区", province: "贵州省" },
  { name: "安顺龙宫景区", province: "贵州省" },
  { name: "毕节百里杜鹃景区", province: "贵州省" },
  { name: "黔南州荔波樟江景区", province: "贵州省" },
  { name: "贵阳花溪青岩古镇景区", province: "贵州省" },
  { name: "铜仁梵净山旅游区", province: "贵州省" },
  { name: "黔东南州镇远古城旅游景区", province: "贵州省" },
  { name: "遵义赤水丹霞旅游区", province: "贵州省" },
  { name: "六盘水野玉海山地旅游度假区", province: "贵州省" },
  { name: "毕节市织金洞景区", province: "贵州省" },
  { name: "黔西南州万峰林景区", province: "贵州省" },
  { name: "昆明石林风景区", province: "云南省" },
  { name: "丽江玉龙雪山景区", province: "云南省" },
  { name: "丽江古城景区", province: "云南省" },
  { name: "大理崇圣寺三塔文化旅游区", province: "云南省" },
  { name: "西双版纳热带植物园", province: "云南省" },
  { name: "迪庆香格里拉普达措景区", province: "云南省" },
  { name: "腾冲火山热海旅游区", province: "云南省" },
  { name: "昆明世博园景区", province: "云南省" },
  { name: "保山和顺古镇景区", province: "云南省" },
  { name: "曲靖珠江源风景区", province: "云南省" },
  { name: "文山州普者黑旅游景区", province: "云南省" },
  { name: "拉萨布达拉宫景区", province: "西藏自治区" },
  { name: "拉萨大昭寺景区", province: "西藏自治区" },
  { name: "林芝巴松措景区", province: "西藏自治区" },
  { name: "日喀则扎什伦布寺景区", province: "西藏自治区" },
  { name: "山南雅砻河风景名胜区", province: "西藏自治区" },
  { name: "林芝市雅鲁藏布大峡谷景区", province: "西藏自治区" },
  { name: "西安秦始皇兵马俑博物馆", province: "陕西省" },
  { name: "西安华清池景区", province: "陕西省" },
  { name: "延安黄陵县黄帝陵景区", province: "陕西省" },
  { name: "西安大雁塔-大唐芙蓉园景区", province: "陕西省" },
  { name: "渭南华阴市华山景区", province: "陕西省" },
  { name: "宝鸡扶风县法门寺佛文化景区", province: "陕西省" },
  { name: "商洛金丝峡景区", province: "陕西省" },
  { name: "宝鸡太白山旅游景区", province: "陕西省" },
  { name: "西安城墙-碑林历史文化景区", province: "陕西省" },
  { name: "延安革命纪念地景区", province: "陕西省" },
  { name: "榆林镇北台景区", province: "陕西省" },
  { name: "汉中青木川古镇景区", province: "陕西省" },
  { name: "安康瀛湖旅游景区", province: "陕西省" },
  { name: "西安市华清宫景区", province: "陕西省" },
  { name: "西安市大明宫旅游景区", province: "陕西省" },
  { name: "延安市延川黄河乾坤湾景区", province: "陕西省" },
  { name: "咸阳市乾陵景区", province: "陕西省" },
  { name: "嘉峪关文物景区", province: "甘肃省" },
  { name: "平凉崆峒山风景名胜区", province: "甘肃省" },
  { name: "天水麦积山景区", province: "甘肃省" },
  { name: "酒泉敦煌鸣沙山月牙泉景区", province: "甘肃省" },
  { name: "兰州黄河铁桥-白塔山风景区", province: "甘肃省" },
  { name: "张掖七彩丹霞景区", province: "甘肃省" },
  { name: "临夏炳灵寺石窟景区", province: "甘肃省" },
  { name: "陇南市官鹅沟景区", province: "甘肃省" },
  { name: "甘南州冶力关旅游区", province: "甘肃省" },
  { name: "青海湖景区", province: "青海省" },
  { name: "湟中塔尔寺景区", province: "青海省" },
  { name: "海东互助土族故土园", province: "青海省" },
  { name: "海北州阿咪东索景区", province: "青海省" },
  { name: "石嘴山沙湖旅游景区", province: "宁夏回族自治区" },
  { name: "中卫沙坡头旅游景区", province: "宁夏回族自治区" },
  { name: "银川镇北堡西部影视城", province: "宁夏回族自治区" },
  { name: "灵武水洞沟旅游区", province: "宁夏回族自治区" },
  { name: "吴忠青铜峡黄河大峡谷", province: "宁夏回族自治区" },
  { name: "固原市六盘山红军长征旅游区", province: "宁夏回族自治区" },
  { name: "乌鲁木齐天山天池风景名胜区", province: "新疆维吾尔自治区" },
  { name: "吐鲁番葡萄沟风景区", province: "新疆维吾尔自治区" },
  { name: "阿勒泰喀纳斯景区", province: "新疆维吾尔自治区" },
  { name: "伊犁那拉提旅游风景区", province: "新疆维吾尔自治区" },
  { name: "阿勒泰富蕴可可托海景区", province: "新疆维吾尔自治区" },
  { name: "喀什泽普金湖杨景区", province: "新疆维吾尔自治区" },
  { name: "巴音郭楞博斯腾湖景区", province: "新疆维吾尔自治区" },
  { name: "乌鲁木齐天山大峡谷景区", province: "新疆维吾尔自治区" },
  { name: "喀什老城景区", province: "新疆维吾尔自治区" },
  { name: "伊犁喀拉峻景区", province: "新疆维吾尔自治区" },
  { name: "巴州和静巴音布鲁克景区", province: "新疆维吾尔自治区" },
  { name: "哈密巴里坤古城景区", province: "新疆维吾尔自治区" },
  { name: "阿克苏天山神木园景区", province: "新疆维吾尔自治区" },
  { name: "和田昆仑山景区", province: "新疆维吾尔自治区" },
  { name: "塔城乌苏佛山国家森林公园", province: "新疆维吾尔自治区" },
  { name: "阿勒泰五彩滩景区", province: "新疆维吾尔自治区" },
  { name: "克拉玛依魔鬼城景区", province: "新疆维吾尔自治区" },
  { name: "喀什地区喀什古城景区", province: "新疆维吾尔自治区" },
  { name: "喀什地区帕米尔旅游区", province: "新疆维吾尔自治区" },
  { name: "博尔塔拉蒙古自治州赛里木湖景区", province: "新疆维吾尔自治区" },
  { name: "昌吉回族自治州江布拉克景区", province: "新疆维吾尔自治区" },
  { name: "阿克苏地区天山托木尔景区", province: "新疆维吾尔自治区" },
  { name: "兵团十师185团白沙湖景区", province: "新疆维吾尔自治区" },
  { name: "兵团阿拉尔市塔克拉玛干·三五九旅文化旅游区", province: "新疆维吾尔自治区" },
  { name: "香港迪士尼乐园", province: "香港特别行政区" },
  { name: "澳门威尼斯人度假村酒店", province: "澳门特别行政区" },
  { name: "台北故宫博物院", province: "台湾地区" },
  { name: "南投日月潭国家风景区", province: "台湾地区" }
];

// 判断是否是官方5A级景区
function isOfficial5ASpot(name: string, province: string): boolean {
  return official5ASpots.some(official => 
    official.name === name && official.province === province
  );
}

async function removeNon5ASpots() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/travel-map');
    console.log('MongoDB 连接成功');

    const allSpots = await ScenicSpot.find({});
    console.log(`数据库中共有 ${allSpots.length} 个景区`);

    const toDelete = [];
    const toKeep = [];

    for (const spot of allSpots) {
      if (spot.name && spot.province && isOfficial5ASpot(spot.name, spot.province)) {
        toKeep.push(spot);
      } else {
        toDelete.push(spot);
      }
    }

    console.log(`\n需要保留的5A级景区: ${toKeep.length} 个`);
    console.log(`需要删除的非5A级景区: ${toDelete.length} 个`);

    if (toDelete.length > 0) {
      console.log('\n将删除以下景区:');
      toDelete.forEach((spot, index) => {
        console.log(`${index + 1}. ${spot.name} (${spot.province})`);
      });

      // 删除非5A级景区
      const deleteResult = await ScenicSpot.deleteMany({
        _id: { $in: toDelete.map(s => s._id) }
      });
      
      console.log(`\n成功删除 ${deleteResult.deletedCount} 个非5A级景区`);
    } else {
      console.log('\n没有需要删除的景区');
    }

    // 验证删除后的数量
    const remainingCount = await ScenicSpot.countDocuments();
    console.log(`\n删除后数据库中共有 ${remainingCount} 个景区`);

  } catch (error) {
    console.error('错误:', error);
  } finally {
    await mongoose.connection.close();
  }
}

removeNon5ASpots();
